apiVersion: v1
kind: Pod
metadata:
  name: nginx-limit
  labels:
    name: nginx-limit
spec:
  containers:
    - name: nginx-limit
      image: nginx:latest
      resources:
        requests:
          memory: "128Mi"
          cpu: "128m"
        limits:
          memory: "128Mi"
          cpu: "200m"
      ports:
        - containerPort: 80
