apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  labels:
    name: nginx
spec:
  containers:
    - name: nginx
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "128m"
      ports:
        - containerPort: 80
