apiVersion: apps/v1
kind: ReplicaSet
metadata:
     name: nginx-volume
spec:
     replicas: 2
     selector:
          matchLabels:
               name: nginx-volume
     template:
          metadata:
               labels:
                    name: nginx-volume
          spec:
               volumes:
                    - name: html
                      emptyDir: {}
               containers:
                    - name: nginx-volume
                      image: nginx:latest
                      ports:
                           - containerPort: 80
                      volumeMounts:
                           - mountPath: /usr/share/nginx/html
                             name: html

---
apiVersion: v1
kind: Service
metadata:
     name: nginx-service-volume
spec:
     selector:
          name: nginx-volume
     type: NodePort
     ports:
          - port: 8080
            targetPort: 80
            nodePort: 30001
