apiVersion: batch/v1

kind: CronJob

metadata:
     name: nodejs-croonjob

spec:
     schedule: "* * * * *"

     jobTemplate:
          spec:
               template:
                    spec:
                         containers:
                              - name: nodejs-croonjob
                                image: rizkyperdana28/nodejs-job
                         restartPolicy: Never
