apiVersion: apps/v1
kind: DaemonSet
metadata:
     name: nginx-daemonset
     labels:
          name: nginx
spec:
     selector:
          matchLabels:
               name: nginx-daemonset
     template:
          metadata:
               labels:
                    name: nginx-daemonset
          spec:
               containers:
                    - name: nginx-daemonset
                      image: nginx:latest
                      resources:
                           limits:
                                memory: 200Mi
                           requests:
                                cpu: 100m
                                memory: 100Mi
