apiVersion: apps/v1
kind: ReplicaSet
metadata:
     name: nginx
     labels:
          app: guestbook
          name: nginx-replica

spec:
     # modify replicas according to your case
     replicas: 2
     selector:
          matchLabels:
               name: nginx
     template:
          metadata:
               labels:
                    name: nginx
          spec:
               containers:
                    - name: nginx
                      image: nginx:latest
